# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
schedule: # execute every 12 hours
    - cron: "* */12 * * *" 

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
  name: Jobs to update datas
    runs-on: ubuntu-latest
       # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Soraiaca
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses:  crazy-max/ghaction-github-pages@v2.1.3
      with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     
